application:  zaqwsxedce
version: beta-7
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /.*
  script: DRLchecker.py
